name: connect
description: Application for Connect service

# version name + version number(should be bigger than 0)
version: 1.3.3+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_sendbird_plugin:
    path: plugins/flutter_sendbird_plugin

  # firebase
  firebase_core: 0.4.4
  firebase_analytics: ^5.0.9
  firebase_crashlytics: ^0.1.2+3
  firebase_messaging: 6.0.16
  firebase_performance: ^0.3.1+5
  firebase_dynamic_links: ^0.5.0+9

  # http
  http: ^0.12.0+2
  json_serializable: ^3.2.3

  #rx dart
  rxdart: ^0.23.1

  # nosql database
  sembast: ^2.1.2
  path_provider: ^1.5.0

  # bloc
  flutter_bloc: ^6.0.2
  equatable: ^1.0.1

  # connectivity
  connectivity: ^0.4.6

  # webview
  webview_flutter: ^1.0.7

  url_launcher: ^5.3.0

  # ad id for getting unique id of device
  unique_ids: ^1.0.10

  # to get package info.
  package_info: ^0.4.0+12

  # to support multi-screen
  multiscreen: ^1.2.1

  # notifications
  flutter_local_notifications: ^4.0.1+2
  notification_permissions: ^0.4.3

  # permission
  permission_handler: ^5.0.1+1

  # calendar ui
  expandable: ^3.0.1
  expandable_card: ^0.0.3+1
  table_calendar: ^2.2.1
  simple_gesture_detector: ^0.1.4

  # collection
  collection: ^1.14.11

  # show html format
  flutter_html: ^0.11.1

  # sprintf for StringKey formatting
  sprintf: ^4.0.2

  # Custom Calendar UI
  percent_indicator: 2.1.5

  # provider
  provider: ^4.0.1

  # intl for DateTime Formatting
  intl: ^0.16.0

  # video player for youtube
  chewie: ^0.9.8+1

  # image loading library
  cached_network_image: ^2.0.0

  # to get us states
  us_states: ^1.0.3

  #force update app from app store and play store
  open_appstore: ^1.0.2

  # show progress on severity checking.
  step_progress_indicator: ^0.2.1+4

  # in app purchase
  in_app_purchase: 0.3.4+16

  # foreground (for android)
  flutter_foreground_plugin: ^0.6.0

  # share
  share:
    git:
      url: https://github.com/pboos/plugins.git
      path: packages/share
      ref: feature/shareFile

  # facebook app event
  #  facebook_app_events: ^0.7.0
  # facebook_analytics
  facebook_analytics: ^0.1.4

  # swiper
  flutter_swiper: ^1.1.6

  # datetime picker
  flutter_datetime_picker: ^1.4.0

  # apple login
  sign_in_with_apple: ^2.5.4

  # facebook login
  flutter_facebook_login: 3.0.0

  # staggered grid view
  flutter_staggered_grid_view: ^0.3.2

  # image picker
  image_picker: ^0.6.7+12

  # multi image picker
  multi_image_picker: ^4.7.14

  # dotted border
  dotted_border: ^1.0.6

  # uuid
  uuid: ^2.2.2

  # jwt decoder
  jwt_decoder: ^1.0.3

  #flutter absolute path
  flutter_absolute_path: ^1.0.6

  # tuple
  tuple: ^1.0.3

  # shared preferences
  shared_preferences: ^0.5.12+4

  # phoenix
  flutter_phoenix: ^0.1.0

  # toast
  fluttertoast: ^7.1.8

  # health
  health: ^3.0.3

  # pedometer
  pedometer: ^2.1.0

  # in app review
  in_app_review: ^1.0.4

  # fi chart
  fl_chart: ^0.12.3

  foreground_service: ^2.0.1+1

  # google sign in
  google_sign_in: ^4.5.9

  # sliding up panel
  sliding_up_panel: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/ic_rehabit_icon.png"
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/illust_therapist.png
    - assets/images/illust_empty.png
    - assets/images/illust_no_noti.png
    - assets/images/ic_check_mission_complete.png
    - assets/images/illust_reading.png
    - assets/images/illust_video.png
    - assets/images/illust_exercise_basics.png
    - assets/images/illust_activity.png
    - assets/images/illust_no_mission.png
    - assets/images/ic_chevron_right.png
    - assets/images/ic_check_circle_green.png
    - assets/images/ic_time.png
    - assets/images/ic_calendar.png
    - assets/images/ic_result.png
    - assets/images/ic_setting.png
    - assets/images/ic_user.png
    - assets/images/ic_video.png
    - assets/images/ic_group_fill.png
    - assets/images/ic_message.png
    - assets/images/ic_swich_videocall.png
    - assets/images/img_connect.png
    - assets/images/ic_arrow_left.png
    - assets/images/ic_star.png
    - assets/images/ic_radio_default.png
    - assets/images/ic_radio_select.png
    - assets/images/img_left_default.png
    - assets/images/img_left_select.png
    - assets/images/img_right_default.png
    - assets/images/img_right_select.png
    - assets/images/ic_checkbox_default.png
    - assets/images/ic_checkbox_select.png
    - assets/images/bg_image_default.png
    - assets/images/img_mission_completed.png
    - assets/images/img_therapist_photo.png
    - assets/images/ic_close_circle.png
    - assets/images/ic_notification_circle.png
    - assets/images/ic_menu.png
    - assets/images/ic_notification.png
    - assets/images/ic_wifi.png
    - assets/images/img_logo_connect.png
    - assets/images/ic_symbol_gray.png
    - assets/images/ic_check_circle_disabled.png
    - assets/images/ic_check_circle.png
    - assets/images/ic_warning.png
    - assets/images/ic_wifi_error.png
    - assets/images/ic_mail.png
    - assets/images/ic_logout.png
    - assets/images/ic_chevron_left.png
    - assets/images/ic_check_circle_white.png
    - assets/images/radio_default.png
    - assets/images/radio_select.png
    - assets/images/
    - assets/images/intro/
    - assets/images/sign_up/
    - assets/images/first_login/
    - assets/images/profile/
    - assets/images/goal/
    - assets/images/diary/
    - assets/images/vip/
    - assets/images/quiz/
    - assets/images/rank/
    - assets/images/bottom_navigation/
    - assets/images/logo/
    - assets/images/my_report/
    - assets/images/tracker/
    - assets/images/bookmark/
    - assets/images/mission/

  fonts:
    - family: manrope
      fonts:
        - asset: assets/fonts/manrope-extrabold.ttf
          weight: 700
        - asset: assets/fonts/manrope-bold.ttf
          weight: 600
        - asset: assets/fonts/manrope-semibold.ttf
          weight: 500
        - asset: assets/fonts/manrope-medium.ttf
          weight: 400
        - asset: assets/fonts/manrope-regular.ttf
          weight: 300
        - asset: assets/fonts/manrope-light.ttf
          weight: 200
        - asset: assets/fonts/manrope-thin.ttf
          weight: 100